//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\v-adai\Documents\Visual Studio 2015\Projects\TxMark\TxMark.Antlr\MarkdownPreprocessor.g4 by ANTLR 4.5-SNAPSHOT

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace TxMark.Compiler {
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using System.Collections.Generic;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5-SNAPSHOT")]
[System.CLSCompliant(false)]
public partial class MarkdownPreprocessorParser : Parser {
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, DIGITS=5, PUNCTUATION=6, TAB=7, SPACE=8, 
		CARRIAGE_RETURN=9, NON_WHITESPACE=10;
	public const int
		RULE_document = 0, RULE_content = 1, RULE_line = 2, RULE_list = 3, RULE_listItem = 4, 
		RULE_indentedText = 5, RULE_listItemIndicator = 6, RULE_blockquote = 7, 
		RULE_blockquoteItem = 8, RULE_blockQuoteElement = 9, RULE_blockQuoteListItem = 10, 
		RULE_blockquoteIndicator = 11, RULE_heading = 12, RULE_headingIndicator = 13, 
		RULE_textLine = 14, RULE_paragraph_end = 15, RULE_text = 16, RULE_nonWhitespace = 17, 
		RULE_whitespace = 18, RULE_space = 19, RULE_tab = 20, RULE_carriageReturn = 21, 
		RULE_softCarriageReturn = 22, RULE_hardCarriageReturn = 23;
	public static readonly string[] ruleNames = {
		"document", "content", "line", "list", "listItem", "indentedText", "listItemIndicator", 
		"blockquote", "blockquoteItem", "blockQuoteElement", "blockQuoteListItem", 
		"blockquoteIndicator", "heading", "headingIndicator", "textLine", "paragraph_end", 
		"text", "nonWhitespace", "whitespace", "space", "tab", "carriageReturn", 
		"softCarriageReturn", "hardCarriageReturn"
	};

	private static readonly string[] _LiteralNames = {
		null, "'*'", "'.'", "'>'", "'#'", null, null, "'\t'", "' '"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, "DIGITS", "PUNCTUATION", "TAB", "SPACE", 
		"CARRIAGE_RETURN", "NON_WHITESPACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[System.Obsolete("Use Vocabulary instead.")]
	public static readonly string[] tokenNames = GenerateTokenNames(DefaultVocabulary, _SymbolicNames.Length);

	private static string[] GenerateTokenNames(IVocabulary vocabulary, int length) {
		string[] tokenNames = new string[length];
		for (int i = 0; i < tokenNames.Length; i++) {
			tokenNames[i] = vocabulary.GetLiteralName(i);
			if (tokenNames[i] == null) {
				tokenNames[i] = vocabulary.GetSymbolicName(i);
			}

			if (tokenNames[i] == null) {
				tokenNames[i] = "<INVALID>";
			}
		}

		return tokenNames;
	}

	[System.Obsolete]
	public override string[] TokenNames
	{
		get
		{
			return tokenNames;
		}
	}

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "MarkdownPreprocessor.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	public MarkdownPreprocessorParser(ITokenStream input)
		: base(input)
	{
		_interp = new ParserATNSimulator(this,_ATN);
	}
	public partial class DocumentContext : ParserRuleContext {
		public ContentContext content() {
			return GetRuleContext<ContentContext>(0);
		}
		public ITerminalNode Eof() { return GetToken(MarkdownPreprocessorParser.Eof, 0); }
		public DocumentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_document; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterDocument(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitDocument(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDocument(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DocumentContext document() {
		DocumentContext _localctx = new DocumentContext(_ctx, State);
		EnterRule(_localctx, 0, RULE_document);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 48; content();
			State = 49; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ContentContext : ParserRuleContext {
		public LineContext[] line() {
			return GetRuleContexts<LineContext>();
		}
		public LineContext line(int i) {
			return GetRuleContext<LineContext>(i);
		}
		public ContentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_content; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterContent(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitContent(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitContent(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ContentContext content() {
		ContentContext _localctx = new ContentContext(_ctx, State);
		EnterRule(_localctx, 2, RULE_content);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 54;
			_errHandler.Sync(this);
			_la = _input.La(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__2) | (1L << T__3) | (1L << DIGITS) | (1L << PUNCTUATION) | (1L << TAB) | (1L << SPACE) | (1L << CARRIAGE_RETURN) | (1L << NON_WHITESPACE))) != 0)) {
				{
				{
				State = 51; line();
				}
				}
				State = 56;
				_errHandler.Sync(this);
				_la = _input.La(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LineContext : ParserRuleContext {
		public HeadingContext heading() {
			return GetRuleContext<HeadingContext>(0);
		}
		public CarriageReturnContext carriageReturn() {
			return GetRuleContext<CarriageReturnContext>(0);
		}
		public ListContext list() {
			return GetRuleContext<ListContext>(0);
		}
		public BlockquoteContext blockquote() {
			return GetRuleContext<BlockquoteContext>(0);
		}
		public TextLineContext textLine() {
			return GetRuleContext<TextLineContext>(0);
		}
		public Paragraph_endContext paragraph_end() {
			return GetRuleContext<Paragraph_endContext>(0);
		}
		public LineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_line; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterLine(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitLine(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLine(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LineContext line() {
		LineContext _localctx = new LineContext(_ctx, State);
		EnterRule(_localctx, 4, RULE_line);
		try {
			State = 66;
			switch ( Interpreter.AdaptivePredict(_input,1,_ctx) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 57; heading();
				State = 58; carriageReturn();
				}
				break;

			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 60; list();
				}
				break;

			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 61; blockquote();
				}
				break;

			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 62; textLine();
				State = 63; carriageReturn();
				}
				break;

			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 65; paragraph_end();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ListContext : ParserRuleContext {
		public ListItemContext[] listItem() {
			return GetRuleContexts<ListItemContext>();
		}
		public ListItemContext listItem(int i) {
			return GetRuleContext<ListItemContext>(i);
		}
		public CarriageReturnContext[] carriageReturn() {
			return GetRuleContexts<CarriageReturnContext>();
		}
		public CarriageReturnContext carriageReturn(int i) {
			return GetRuleContext<CarriageReturnContext>(i);
		}
		public IndentedTextContext[] indentedText() {
			return GetRuleContexts<IndentedTextContext>();
		}
		public IndentedTextContext indentedText(int i) {
			return GetRuleContext<IndentedTextContext>(i);
		}
		public ListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_list; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterList(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitList(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ListContext list() {
		ListContext _localctx = new ListContext(_ctx, State);
		EnterRule(_localctx, 6, RULE_list);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 74;
			_errHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					State = 74;
					switch (_input.La(1)) {
					case T__0:
					case DIGITS:
						{
						State = 68; listItem();
						State = 69; carriageReturn();
						}
						break;
					case TAB:
					case SPACE:
						{
						State = 71; indentedText();
						State = 72; carriageReturn();
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 76;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,3,_ctx);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ListItemContext : ParserRuleContext {
		public TextContext text() {
			return GetRuleContext<TextContext>(0);
		}
		public ListItemIndicatorContext[] listItemIndicator() {
			return GetRuleContexts<ListItemIndicatorContext>();
		}
		public ListItemIndicatorContext listItemIndicator(int i) {
			return GetRuleContext<ListItemIndicatorContext>(i);
		}
		public WhitespaceContext[] whitespace() {
			return GetRuleContexts<WhitespaceContext>();
		}
		public WhitespaceContext whitespace(int i) {
			return GetRuleContext<WhitespaceContext>(i);
		}
		public ListItemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_listItem; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterListItem(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitListItem(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitListItem(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ListItemContext listItem() {
		ListItemContext _localctx = new ListItemContext(_ctx, State);
		EnterRule(_localctx, 8, RULE_listItem);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 82;
			_errHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					{
					State = 78; listItemIndicator();
					State = 80;
					_la = _input.La(1);
					if (_la==TAB || _la==SPACE) {
						{
						State = 79; whitespace();
						}
					}

					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 84;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,5,_ctx);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber );
			State = 86; text();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IndentedTextContext : ParserRuleContext {
		public TextContext text() {
			return GetRuleContext<TextContext>(0);
		}
		public SpaceContext[] space() {
			return GetRuleContexts<SpaceContext>();
		}
		public SpaceContext space(int i) {
			return GetRuleContext<SpaceContext>(i);
		}
		public TabContext[] tab() {
			return GetRuleContexts<TabContext>();
		}
		public TabContext tab(int i) {
			return GetRuleContext<TabContext>(i);
		}
		public IndentedTextContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_indentedText; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterIndentedText(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitIndentedText(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIndentedText(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IndentedTextContext indentedText() {
		IndentedTextContext _localctx = new IndentedTextContext(_ctx, State);
		EnterRule(_localctx, 10, RULE_indentedText);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 101;
			switch (_input.La(1)) {
			case TAB:
				{
				State = 89;
				_errHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 88; tab();
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 91;
					_errHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(_input,6,_ctx);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber );
				}
				break;
			case SPACE:
				{
				State = 93; space();
				State = 94; space();
				State = 95; space();
				State = 97;
				_errHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 96; space();
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 99;
					_errHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(_input,7,_ctx);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber );
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 107;
			_errHandler.Sync(this);
			_la = _input.La(1);
			while (_la==TAB || _la==SPACE) {
				{
				State = 105;
				switch (_input.La(1)) {
				case TAB:
					{
					State = 103; tab();
					}
					break;
				case SPACE:
					{
					State = 104; space();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 109;
				_errHandler.Sync(this);
				_la = _input.La(1);
			}
			State = 110; text();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ListItemIndicatorContext : ParserRuleContext {
		public ITerminalNode DIGITS() { return GetToken(MarkdownPreprocessorParser.DIGITS, 0); }
		public ListItemIndicatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_listItemIndicator; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterListItemIndicator(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitListItemIndicator(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitListItemIndicator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ListItemIndicatorContext listItemIndicator() {
		ListItemIndicatorContext _localctx = new ListItemIndicatorContext(_ctx, State);
		EnterRule(_localctx, 12, RULE_listItemIndicator);
		try {
			State = 115;
			switch (_input.La(1)) {
			case T__0:
				EnterOuterAlt(_localctx, 1);
				{
				State = 112; Match(T__0);
				}
				break;
			case DIGITS:
				EnterOuterAlt(_localctx, 2);
				{
				State = 113; Match(DIGITS);
				State = 114; Match(T__1);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockquoteContext : ParserRuleContext {
		public BlockquoteItemContext[] blockquoteItem() {
			return GetRuleContexts<BlockquoteItemContext>();
		}
		public BlockquoteItemContext blockquoteItem(int i) {
			return GetRuleContext<BlockquoteItemContext>(i);
		}
		public CarriageReturnContext[] carriageReturn() {
			return GetRuleContexts<CarriageReturnContext>();
		}
		public CarriageReturnContext carriageReturn(int i) {
			return GetRuleContext<CarriageReturnContext>(i);
		}
		public IndentedTextContext[] indentedText() {
			return GetRuleContexts<IndentedTextContext>();
		}
		public IndentedTextContext indentedText(int i) {
			return GetRuleContext<IndentedTextContext>(i);
		}
		public BlockquoteContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_blockquote; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterBlockquote(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitBlockquote(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlockquote(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockquoteContext blockquote() {
		BlockquoteContext _localctx = new BlockquoteContext(_ctx, State);
		EnterRule(_localctx, 14, RULE_blockquote);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 123;
			_errHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					State = 123;
					switch (_input.La(1)) {
					case T__2:
						{
						State = 117; blockquoteItem();
						State = 118; carriageReturn();
						}
						break;
					case TAB:
					case SPACE:
						{
						State = 120; indentedText();
						State = 121; carriageReturn();
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 125;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,13,_ctx);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockquoteItemContext : ParserRuleContext {
		public BlockQuoteElementContext blockQuoteElement() {
			return GetRuleContext<BlockQuoteElementContext>(0);
		}
		public BlockquoteIndicatorContext[] blockquoteIndicator() {
			return GetRuleContexts<BlockquoteIndicatorContext>();
		}
		public BlockquoteIndicatorContext blockquoteIndicator(int i) {
			return GetRuleContext<BlockquoteIndicatorContext>(i);
		}
		public WhitespaceContext[] whitespace() {
			return GetRuleContexts<WhitespaceContext>();
		}
		public WhitespaceContext whitespace(int i) {
			return GetRuleContext<WhitespaceContext>(i);
		}
		public BlockquoteItemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_blockquoteItem; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterBlockquoteItem(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitBlockquoteItem(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlockquoteItem(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockquoteItemContext blockquoteItem() {
		BlockquoteItemContext _localctx = new BlockquoteItemContext(_ctx, State);
		EnterRule(_localctx, 16, RULE_blockquoteItem);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 131;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 127; blockquoteIndicator();
				State = 129;
				switch ( Interpreter.AdaptivePredict(_input,14,_ctx) ) {
				case 1:
					{
					State = 128; whitespace();
					}
					break;
				}
				}
				}
				State = 133;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( _la==T__2 );
			State = 135; blockQuoteElement();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockQuoteElementContext : ParserRuleContext {
		public HeadingContext heading() {
			return GetRuleContext<HeadingContext>(0);
		}
		public BlockQuoteListItemContext blockQuoteListItem() {
			return GetRuleContext<BlockQuoteListItemContext>(0);
		}
		public TextLineContext textLine() {
			return GetRuleContext<TextLineContext>(0);
		}
		public BlockQuoteElementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_blockQuoteElement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterBlockQuoteElement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitBlockQuoteElement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlockQuoteElement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockQuoteElementContext blockQuoteElement() {
		BlockQuoteElementContext _localctx = new BlockQuoteElementContext(_ctx, State);
		EnterRule(_localctx, 18, RULE_blockQuoteElement);
		try {
			State = 140;
			switch ( Interpreter.AdaptivePredict(_input,16,_ctx) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 137; heading();
				}
				break;

			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 138; blockQuoteListItem();
				}
				break;

			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 139; textLine();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockQuoteListItemContext : ParserRuleContext {
		public TextContext text() {
			return GetRuleContext<TextContext>(0);
		}
		public ListItemIndicatorContext[] listItemIndicator() {
			return GetRuleContexts<ListItemIndicatorContext>();
		}
		public ListItemIndicatorContext listItemIndicator(int i) {
			return GetRuleContext<ListItemIndicatorContext>(i);
		}
		public WhitespaceContext[] whitespace() {
			return GetRuleContexts<WhitespaceContext>();
		}
		public WhitespaceContext whitespace(int i) {
			return GetRuleContext<WhitespaceContext>(i);
		}
		public BlockQuoteListItemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_blockQuoteListItem; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterBlockQuoteListItem(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitBlockQuoteListItem(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlockQuoteListItem(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockQuoteListItemContext blockQuoteListItem() {
		BlockQuoteListItemContext _localctx = new BlockQuoteListItemContext(_ctx, State);
		EnterRule(_localctx, 20, RULE_blockQuoteListItem);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 146;
			_errHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					{
					State = 142; listItemIndicator();
					State = 144;
					_la = _input.La(1);
					if (_la==TAB || _la==SPACE) {
						{
						State = 143; whitespace();
						}
					}

					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 148;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,18,_ctx);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber );
			State = 150; text();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockquoteIndicatorContext : ParserRuleContext {
		public BlockquoteIndicatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_blockquoteIndicator; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterBlockquoteIndicator(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitBlockquoteIndicator(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlockquoteIndicator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockquoteIndicatorContext blockquoteIndicator() {
		BlockquoteIndicatorContext _localctx = new BlockquoteIndicatorContext(_ctx, State);
		EnterRule(_localctx, 22, RULE_blockquoteIndicator);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 152; Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HeadingContext : ParserRuleContext {
		public WhitespaceContext whitespace() {
			return GetRuleContext<WhitespaceContext>(0);
		}
		public TextContext text() {
			return GetRuleContext<TextContext>(0);
		}
		public HeadingIndicatorContext[] headingIndicator() {
			return GetRuleContexts<HeadingIndicatorContext>();
		}
		public HeadingIndicatorContext headingIndicator(int i) {
			return GetRuleContext<HeadingIndicatorContext>(i);
		}
		public HeadingContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_heading; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterHeading(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitHeading(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHeading(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public HeadingContext heading() {
		HeadingContext _localctx = new HeadingContext(_ctx, State);
		EnterRule(_localctx, 24, RULE_heading);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 155;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 154; headingIndicator();
				}
				}
				State = 157;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( _la==T__3 );
			State = 159; whitespace();
			State = 160; text();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HeadingIndicatorContext : ParserRuleContext {
		public HeadingIndicatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_headingIndicator; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterHeadingIndicator(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitHeadingIndicator(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHeadingIndicator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public HeadingIndicatorContext headingIndicator() {
		HeadingIndicatorContext _localctx = new HeadingIndicatorContext(_ctx, State);
		EnterRule(_localctx, 26, RULE_headingIndicator);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 162; Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TextLineContext : ParserRuleContext {
		public TextContext text() {
			return GetRuleContext<TextContext>(0);
		}
		public WhitespaceContext[] whitespace() {
			return GetRuleContexts<WhitespaceContext>();
		}
		public WhitespaceContext whitespace(int i) {
			return GetRuleContext<WhitespaceContext>(i);
		}
		public TextLineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_textLine; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterTextLine(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitTextLine(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTextLine(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TextLineContext textLine() {
		TextLineContext _localctx = new TextLineContext(_ctx, State);
		EnterRule(_localctx, 28, RULE_textLine);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 167;
			_errHandler.Sync(this);
			_la = _input.La(1);
			while (_la==TAB || _la==SPACE) {
				{
				{
				State = 164; whitespace();
				}
				}
				State = 169;
				_errHandler.Sync(this);
				_la = _input.La(1);
			}
			State = 170; text();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Paragraph_endContext : ParserRuleContext {
		public CarriageReturnContext carriageReturn() {
			return GetRuleContext<CarriageReturnContext>(0);
		}
		public WhitespaceContext[] whitespace() {
			return GetRuleContexts<WhitespaceContext>();
		}
		public WhitespaceContext whitespace(int i) {
			return GetRuleContext<WhitespaceContext>(i);
		}
		public Paragraph_endContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_paragraph_end; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterParagraph_end(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitParagraph_end(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParagraph_end(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Paragraph_endContext paragraph_end() {
		Paragraph_endContext _localctx = new Paragraph_endContext(_ctx, State);
		EnterRule(_localctx, 30, RULE_paragraph_end);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 175;
			_errHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(_input,21,_ctx);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					{
					{
					State = 172; whitespace();
					}
					} 
				}
				State = 177;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,21,_ctx);
			}
			State = 178; carriageReturn();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TextContext : ParserRuleContext {
		public NonWhitespaceContext[] nonWhitespace() {
			return GetRuleContexts<NonWhitespaceContext>();
		}
		public NonWhitespaceContext nonWhitespace(int i) {
			return GetRuleContext<NonWhitespaceContext>(i);
		}
		public WhitespaceContext[] whitespace() {
			return GetRuleContexts<WhitespaceContext>();
		}
		public WhitespaceContext whitespace(int i) {
			return GetRuleContext<WhitespaceContext>(i);
		}
		public TextContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_text; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterText(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitText(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitText(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TextContext text() {
		TextContext _localctx = new TextContext(_ctx, State);
		EnterRule(_localctx, 32, RULE_text);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 180; nonWhitespace();
			State = 189;
			_errHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(_input,23,_ctx);
			while ( _alt!=1 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1+1 ) {
					{
					State = 187;
					switch (_input.La(1)) {
					case TAB:
					case SPACE:
						{
						State = 181; whitespace();
						}
						break;
					case DIGITS:
					case PUNCTUATION:
					case NON_WHITESPACE:
						{
						State = 182; nonWhitespace();
						}
						break;
					case T__3:
						{
						State = 183; Match(T__3);
						}
						break;
					case T__0:
						{
						State = 184; Match(T__0);
						}
						break;
					case T__2:
						{
						State = 185; Match(T__2);
						}
						break;
					case T__1:
						{
						State = 186; Match(T__1);
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					} 
				}
				State = 191;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,23,_ctx);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NonWhitespaceContext : ParserRuleContext {
		public ITerminalNode NON_WHITESPACE() { return GetToken(MarkdownPreprocessorParser.NON_WHITESPACE, 0); }
		public ITerminalNode PUNCTUATION() { return GetToken(MarkdownPreprocessorParser.PUNCTUATION, 0); }
		public ITerminalNode DIGITS() { return GetToken(MarkdownPreprocessorParser.DIGITS, 0); }
		public NonWhitespaceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_nonWhitespace; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterNonWhitespace(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitNonWhitespace(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNonWhitespace(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NonWhitespaceContext nonWhitespace() {
		NonWhitespaceContext _localctx = new NonWhitespaceContext(_ctx, State);
		EnterRule(_localctx, 34, RULE_nonWhitespace);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 192;
			_la = _input.La(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << DIGITS) | (1L << PUNCTUATION) | (1L << NON_WHITESPACE))) != 0)) ) {
			_errHandler.RecoverInline(this);
			} else {
				Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WhitespaceContext : ParserRuleContext {
		public SpaceContext space() {
			return GetRuleContext<SpaceContext>(0);
		}
		public TabContext tab() {
			return GetRuleContext<TabContext>(0);
		}
		public WhitespaceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_whitespace; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterWhitespace(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitWhitespace(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWhitespace(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public WhitespaceContext whitespace() {
		WhitespaceContext _localctx = new WhitespaceContext(_ctx, State);
		EnterRule(_localctx, 36, RULE_whitespace);
		try {
			State = 196;
			switch (_input.La(1)) {
			case SPACE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 194; space();
				}
				break;
			case TAB:
				EnterOuterAlt(_localctx, 2);
				{
				State = 195; tab();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SpaceContext : ParserRuleContext {
		public ITerminalNode SPACE() { return GetToken(MarkdownPreprocessorParser.SPACE, 0); }
		public SpaceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_space; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterSpace(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitSpace(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSpace(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SpaceContext space() {
		SpaceContext _localctx = new SpaceContext(_ctx, State);
		EnterRule(_localctx, 38, RULE_space);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 198; Match(SPACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TabContext : ParserRuleContext {
		public ITerminalNode TAB() { return GetToken(MarkdownPreprocessorParser.TAB, 0); }
		public TabContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_tab; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterTab(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitTab(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTab(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TabContext tab() {
		TabContext _localctx = new TabContext(_ctx, State);
		EnterRule(_localctx, 40, RULE_tab);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 200; Match(TAB);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CarriageReturnContext : ParserRuleContext {
		public SoftCarriageReturnContext softCarriageReturn() {
			return GetRuleContext<SoftCarriageReturnContext>(0);
		}
		public HardCarriageReturnContext hardCarriageReturn() {
			return GetRuleContext<HardCarriageReturnContext>(0);
		}
		public CarriageReturnContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_carriageReturn; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterCarriageReturn(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitCarriageReturn(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCarriageReturn(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CarriageReturnContext carriageReturn() {
		CarriageReturnContext _localctx = new CarriageReturnContext(_ctx, State);
		EnterRule(_localctx, 42, RULE_carriageReturn);
		try {
			State = 204;
			switch (_input.La(1)) {
			case CARRIAGE_RETURN:
				EnterOuterAlt(_localctx, 1);
				{
				State = 202; softCarriageReturn();
				}
				break;
			case SPACE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 203; hardCarriageReturn();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SoftCarriageReturnContext : ParserRuleContext {
		public ITerminalNode CARRIAGE_RETURN() { return GetToken(MarkdownPreprocessorParser.CARRIAGE_RETURN, 0); }
		public SoftCarriageReturnContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_softCarriageReturn; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterSoftCarriageReturn(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitSoftCarriageReturn(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSoftCarriageReturn(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SoftCarriageReturnContext softCarriageReturn() {
		SoftCarriageReturnContext _localctx = new SoftCarriageReturnContext(_ctx, State);
		EnterRule(_localctx, 44, RULE_softCarriageReturn);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 206; Match(CARRIAGE_RETURN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HardCarriageReturnContext : ParserRuleContext {
		public SpaceContext[] space() {
			return GetRuleContexts<SpaceContext>();
		}
		public SpaceContext space(int i) {
			return GetRuleContext<SpaceContext>(i);
		}
		public ITerminalNode CARRIAGE_RETURN() { return GetToken(MarkdownPreprocessorParser.CARRIAGE_RETURN, 0); }
		public HardCarriageReturnContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_hardCarriageReturn; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.EnterHardCarriageReturn(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMarkdownPreprocessorListener typedListener = listener as IMarkdownPreprocessorListener;
			if (typedListener != null) typedListener.ExitHardCarriageReturn(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarkdownPreprocessorVisitor<TResult> typedVisitor = visitor as IMarkdownPreprocessorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHardCarriageReturn(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public HardCarriageReturnContext hardCarriageReturn() {
		HardCarriageReturnContext _localctx = new HardCarriageReturnContext(_ctx, State);
		EnterRule(_localctx, 46, RULE_hardCarriageReturn);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 208; space();
			State = 210;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 209; space();
				}
				}
				State = 212;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( _la==SPACE );
			State = 214; Match(CARRIAGE_RETURN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public static readonly string _serializedATN =
		"\x3\xAF6F\x8320\x479D\xB75C\x4880\x1605\x191C\xAB37\x3\f\xDB\x4\x2\t\x2"+
		"\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6\x4\a\t\a\x4\b\t\b\x4\t\t"+
		"\t\x4\n\t\n\x4\v\t\v\x4\f\t\f\x4\r\t\r\x4\xE\t\xE\x4\xF\t\xF\x4\x10\t"+
		"\x10\x4\x11\t\x11\x4\x12\t\x12\x4\x13\t\x13\x4\x14\t\x14\x4\x15\t\x15"+
		"\x4\x16\t\x16\x4\x17\t\x17\x4\x18\t\x18\x4\x19\t\x19\x3\x2\x3\x2\x3\x2"+
		"\x3\x3\a\x3\x37\n\x3\f\x3\xE\x3:\v\x3\x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3"+
		"\x4\x3\x4\x3\x4\x3\x4\x5\x4\x45\n\x4\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3"+
		"\x5\x6\x5M\n\x5\r\x5\xE\x5N\x3\x6\x3\x6\x5\x6S\n\x6\x6\x6U\n\x6\r\x6\xE"+
		"\x6V\x3\x6\x3\x6\x3\a\x6\a\\\n\a\r\a\xE\a]\x3\a\x3\a\x3\a\x3\a\x6\a\x64"+
		"\n\a\r\a\xE\a\x65\x5\ah\n\a\x3\a\x3\a\a\al\n\a\f\a\xE\ao\v\a\x3\a\x3\a"+
		"\x3\b\x3\b\x3\b\x5\bv\n\b\x3\t\x3\t\x3\t\x3\t\x3\t\x3\t\x6\t~\n\t\r\t"+
		"\xE\t\x7F\x3\n\x3\n\x5\n\x84\n\n\x6\n\x86\n\n\r\n\xE\n\x87\x3\n\x3\n\x3"+
		"\v\x3\v\x3\v\x5\v\x8F\n\v\x3\f\x3\f\x5\f\x93\n\f\x6\f\x95\n\f\r\f\xE\f"+
		"\x96\x3\f\x3\f\x3\r\x3\r\x3\xE\x6\xE\x9E\n\xE\r\xE\xE\xE\x9F\x3\xE\x3"+
		"\xE\x3\xE\x3\xF\x3\xF\x3\x10\a\x10\xA8\n\x10\f\x10\xE\x10\xAB\v\x10\x3"+
		"\x10\x3\x10\x3\x11\a\x11\xB0\n\x11\f\x11\xE\x11\xB3\v\x11\x3\x11\x3\x11"+
		"\x3\x12\x3\x12\x3\x12\x3\x12\x3\x12\x3\x12\x3\x12\a\x12\xBE\n\x12\f\x12"+
		"\xE\x12\xC1\v\x12\x3\x13\x3\x13\x3\x14\x3\x14\x5\x14\xC7\n\x14\x3\x15"+
		"\x3\x15\x3\x16\x3\x16\x3\x17\x3\x17\x5\x17\xCF\n\x17\x3\x18\x3\x18\x3"+
		"\x19\x3\x19\x6\x19\xD5\n\x19\r\x19\xE\x19\xD6\x3\x19\x3\x19\x3\x19\x3"+
		"\xBF\x2\x2\x1A\x2\x2\x4\x2\x6\x2\b\x2\n\x2\f\x2\xE\x2\x10\x2\x12\x2\x14"+
		"\x2\x16\x2\x18\x2\x1A\x2\x1C\x2\x1E\x2 \x2\"\x2$\x2&\x2(\x2*\x2,\x2.\x2"+
		"\x30\x2\x2\x3\x4\x2\a\b\f\f\xE5\x2\x32\x3\x2\x2\x2\x4\x38\x3\x2\x2\x2"+
		"\x6\x44\x3\x2\x2\x2\bL\x3\x2\x2\x2\nT\x3\x2\x2\x2\fg\x3\x2\x2\x2\xEu\x3"+
		"\x2\x2\x2\x10}\x3\x2\x2\x2\x12\x85\x3\x2\x2\x2\x14\x8E\x3\x2\x2\x2\x16"+
		"\x94\x3\x2\x2\x2\x18\x9A\x3\x2\x2\x2\x1A\x9D\x3\x2\x2\x2\x1C\xA4\x3\x2"+
		"\x2\x2\x1E\xA9\x3\x2\x2\x2 \xB1\x3\x2\x2\x2\"\xB6\x3\x2\x2\x2$\xC2\x3"+
		"\x2\x2\x2&\xC6\x3\x2\x2\x2(\xC8\x3\x2\x2\x2*\xCA\x3\x2\x2\x2,\xCE\x3\x2"+
		"\x2\x2.\xD0\x3\x2\x2\x2\x30\xD2\x3\x2\x2\x2\x32\x33\x5\x4\x3\x2\x33\x34"+
		"\a\x2\x2\x3\x34\x3\x3\x2\x2\x2\x35\x37\x5\x6\x4\x2\x36\x35\x3\x2\x2\x2"+
		"\x37:\x3\x2\x2\x2\x38\x36\x3\x2\x2\x2\x38\x39\x3\x2\x2\x2\x39\x5\x3\x2"+
		"\x2\x2:\x38\x3\x2\x2\x2;<\x5\x1A\xE\x2<=\x5,\x17\x2=\x45\x3\x2\x2\x2>"+
		"\x45\x5\b\x5\x2?\x45\x5\x10\t\x2@\x41\x5\x1E\x10\x2\x41\x42\x5,\x17\x2"+
		"\x42\x45\x3\x2\x2\x2\x43\x45\x5 \x11\x2\x44;\x3\x2\x2\x2\x44>\x3\x2\x2"+
		"\x2\x44?\x3\x2\x2\x2\x44@\x3\x2\x2\x2\x44\x43\x3\x2\x2\x2\x45\a\x3\x2"+
		"\x2\x2\x46G\x5\n\x6\x2GH\x5,\x17\x2HM\x3\x2\x2\x2IJ\x5\f\a\x2JK\x5,\x17"+
		"\x2KM\x3\x2\x2\x2L\x46\x3\x2\x2\x2LI\x3\x2\x2\x2MN\x3\x2\x2\x2NL\x3\x2"+
		"\x2\x2NO\x3\x2\x2\x2O\t\x3\x2\x2\x2PR\x5\xE\b\x2QS\x5&\x14\x2RQ\x3\x2"+
		"\x2\x2RS\x3\x2\x2\x2SU\x3\x2\x2\x2TP\x3\x2\x2\x2UV\x3\x2\x2\x2VT\x3\x2"+
		"\x2\x2VW\x3\x2\x2\x2WX\x3\x2\x2\x2XY\x5\"\x12\x2Y\v\x3\x2\x2\x2Z\\\x5"+
		"*\x16\x2[Z\x3\x2\x2\x2\\]\x3\x2\x2\x2][\x3\x2\x2\x2]^\x3\x2\x2\x2^h\x3"+
		"\x2\x2\x2_`\x5(\x15\x2`\x61\x5(\x15\x2\x61\x63\x5(\x15\x2\x62\x64\x5("+
		"\x15\x2\x63\x62\x3\x2\x2\x2\x64\x65\x3\x2\x2\x2\x65\x63\x3\x2\x2\x2\x65"+
		"\x66\x3\x2\x2\x2\x66h\x3\x2\x2\x2g[\x3\x2\x2\x2g_\x3\x2\x2\x2hm\x3\x2"+
		"\x2\x2il\x5*\x16\x2jl\x5(\x15\x2ki\x3\x2\x2\x2kj\x3\x2\x2\x2lo\x3\x2\x2"+
		"\x2mk\x3\x2\x2\x2mn\x3\x2\x2\x2np\x3\x2\x2\x2om\x3\x2\x2\x2pq\x5\"\x12"+
		"\x2q\r\x3\x2\x2\x2rv\a\x3\x2\x2st\a\a\x2\x2tv\a\x4\x2\x2ur\x3\x2\x2\x2"+
		"us\x3\x2\x2\x2v\xF\x3\x2\x2\x2wx\x5\x12\n\x2xy\x5,\x17\x2y~\x3\x2\x2\x2"+
		"z{\x5\f\a\x2{|\x5,\x17\x2|~\x3\x2\x2\x2}w\x3\x2\x2\x2}z\x3\x2\x2\x2~\x7F"+
		"\x3\x2\x2\x2\x7F}\x3\x2\x2\x2\x7F\x80\x3\x2\x2\x2\x80\x11\x3\x2\x2\x2"+
		"\x81\x83\x5\x18\r\x2\x82\x84\x5&\x14\x2\x83\x82\x3\x2\x2\x2\x83\x84\x3"+
		"\x2\x2\x2\x84\x86\x3\x2\x2\x2\x85\x81\x3\x2\x2\x2\x86\x87\x3\x2\x2\x2"+
		"\x87\x85\x3\x2\x2\x2\x87\x88\x3\x2\x2\x2\x88\x89\x3\x2\x2\x2\x89\x8A\x5"+
		"\x14\v\x2\x8A\x13\x3\x2\x2\x2\x8B\x8F\x5\x1A\xE\x2\x8C\x8F\x5\x16\f\x2"+
		"\x8D\x8F\x5\x1E\x10\x2\x8E\x8B\x3\x2\x2\x2\x8E\x8C\x3\x2\x2\x2\x8E\x8D"+
		"\x3\x2\x2\x2\x8F\x15\x3\x2\x2\x2\x90\x92\x5\xE\b\x2\x91\x93\x5&\x14\x2"+
		"\x92\x91\x3\x2\x2\x2\x92\x93\x3\x2\x2\x2\x93\x95\x3\x2\x2\x2\x94\x90\x3"+
		"\x2\x2\x2\x95\x96\x3\x2\x2\x2\x96\x94\x3\x2\x2\x2\x96\x97\x3\x2\x2\x2"+
		"\x97\x98\x3\x2\x2\x2\x98\x99\x5\"\x12\x2\x99\x17\x3\x2\x2\x2\x9A\x9B\a"+
		"\x5\x2\x2\x9B\x19\x3\x2\x2\x2\x9C\x9E\x5\x1C\xF\x2\x9D\x9C\x3\x2\x2\x2"+
		"\x9E\x9F\x3\x2\x2\x2\x9F\x9D\x3\x2\x2\x2\x9F\xA0\x3\x2\x2\x2\xA0\xA1\x3"+
		"\x2\x2\x2\xA1\xA2\x5&\x14\x2\xA2\xA3\x5\"\x12\x2\xA3\x1B\x3\x2\x2\x2\xA4"+
		"\xA5\a\x6\x2\x2\xA5\x1D\x3\x2\x2\x2\xA6\xA8\x5&\x14\x2\xA7\xA6\x3\x2\x2"+
		"\x2\xA8\xAB\x3\x2\x2\x2\xA9\xA7\x3\x2\x2\x2\xA9\xAA\x3\x2\x2\x2\xAA\xAC"+
		"\x3\x2\x2\x2\xAB\xA9\x3\x2\x2\x2\xAC\xAD\x5\"\x12\x2\xAD\x1F\x3\x2\x2"+
		"\x2\xAE\xB0\x5&\x14\x2\xAF\xAE\x3\x2\x2\x2\xB0\xB3\x3\x2\x2\x2\xB1\xAF"+
		"\x3\x2\x2\x2\xB1\xB2\x3\x2\x2\x2\xB2\xB4\x3\x2\x2\x2\xB3\xB1\x3\x2\x2"+
		"\x2\xB4\xB5\x5,\x17\x2\xB5!\x3\x2\x2\x2\xB6\xBF\x5$\x13\x2\xB7\xBE\x5"+
		"&\x14\x2\xB8\xBE\x5$\x13\x2\xB9\xBE\a\x6\x2\x2\xBA\xBE\a\x3\x2\x2\xBB"+
		"\xBE\a\x5\x2\x2\xBC\xBE\a\x4\x2\x2\xBD\xB7\x3\x2\x2\x2\xBD\xB8\x3\x2\x2"+
		"\x2\xBD\xB9\x3\x2\x2\x2\xBD\xBA\x3\x2\x2\x2\xBD\xBB\x3\x2\x2\x2\xBD\xBC"+
		"\x3\x2\x2\x2\xBE\xC1\x3\x2\x2\x2\xBF\xC0\x3\x2\x2\x2\xBF\xBD\x3\x2\x2"+
		"\x2\xC0#\x3\x2\x2\x2\xC1\xBF\x3\x2\x2\x2\xC2\xC3\t\x2\x2\x2\xC3%\x3\x2"+
		"\x2\x2\xC4\xC7\x5(\x15\x2\xC5\xC7\x5*\x16\x2\xC6\xC4\x3\x2\x2\x2\xC6\xC5"+
		"\x3\x2\x2\x2\xC7\'\x3\x2\x2\x2\xC8\xC9\a\n\x2\x2\xC9)\x3\x2\x2\x2\xCA"+
		"\xCB\a\t\x2\x2\xCB+\x3\x2\x2\x2\xCC\xCF\x5.\x18\x2\xCD\xCF\x5\x30\x19"+
		"\x2\xCE\xCC\x3\x2\x2\x2\xCE\xCD\x3\x2\x2\x2\xCF-\x3\x2\x2\x2\xD0\xD1\a"+
		"\v\x2\x2\xD1/\x3\x2\x2\x2\xD2\xD4\x5(\x15\x2\xD3\xD5\x5(\x15\x2\xD4\xD3"+
		"\x3\x2\x2\x2\xD5\xD6\x3\x2\x2\x2\xD6\xD4\x3\x2\x2\x2\xD6\xD7\x3\x2\x2"+
		"\x2\xD7\xD8\x3\x2\x2\x2\xD8\xD9\a\v\x2\x2\xD9\x31\x3\x2\x2\x2\x1D\x38"+
		"\x44LNRV]\x65gkmu}\x7F\x83\x87\x8E\x92\x96\x9F\xA9\xB1\xBD\xBF\xC6\xCE"+
		"\xD6";
	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
} // namespace TxMark.Compiler
