//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\v-adai\Documents\Visual Studio 2015\Projects\TxMark\TxMark.Antlr\MarkdownPreprocessor.g4 by ANTLR 4.5.3-SNAPSHOT

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace TxMark.Compiler {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MarkdownPreprocessorParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3-SNAPSHOT")]
[System.CLSCompliant(false)]
public interface IMarkdownPreprocessorVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDocument([NotNull] MarkdownPreprocessorParser.DocumentContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine([NotNull] MarkdownPreprocessorParser.LineContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.carriageReturn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCarriageReturn([NotNull] MarkdownPreprocessorParser.CarriageReturnContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.softCarriageReturn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSoftCarriageReturn([NotNull] MarkdownPreprocessorParser.SoftCarriageReturnContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.hardCarriageReturn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHardCarriageReturn([NotNull] MarkdownPreprocessorParser.HardCarriageReturnContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList([NotNull] MarkdownPreprocessorParser.ListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.listItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListItem([NotNull] MarkdownPreprocessorParser.ListItemContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.indentedText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndentedText([NotNull] MarkdownPreprocessorParser.IndentedTextContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.listItemIndicator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListItemIndicator([NotNull] MarkdownPreprocessorParser.ListItemIndicatorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.blockquote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockquote([NotNull] MarkdownPreprocessorParser.BlockquoteContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.blockquoteItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockquoteItem([NotNull] MarkdownPreprocessorParser.BlockquoteItemContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.blockQuoteElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockQuoteElement([NotNull] MarkdownPreprocessorParser.BlockQuoteElementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.blockQuoteListItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockQuoteListItem([NotNull] MarkdownPreprocessorParser.BlockQuoteListItemContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.blockquoteIndicator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockquoteIndicator([NotNull] MarkdownPreprocessorParser.BlockquoteIndicatorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.heading"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHeading([NotNull] MarkdownPreprocessorParser.HeadingContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.headingIndicator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHeadingIndicator([NotNull] MarkdownPreprocessorParser.HeadingIndicatorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.textLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTextLine([NotNull] MarkdownPreprocessorParser.TextLineContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.paragraph_end"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParagraph_end([NotNull] MarkdownPreprocessorParser.Paragraph_endContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitText([NotNull] MarkdownPreprocessorParser.TextContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.attributeContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeContent([NotNull] MarkdownPreprocessorParser.AttributeContentContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.attributeValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeValue([NotNull] MarkdownPreprocessorParser.AttributeValueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.attributeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeName([NotNull] MarkdownPreprocessorParser.AttributeNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] MarkdownPreprocessorParser.AttributeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.tag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTag([NotNull] MarkdownPreprocessorParser.TagContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.openTag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpenTag([NotNull] MarkdownPreprocessorParser.OpenTagContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.closeTag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCloseTag([NotNull] MarkdownPreprocessorParser.CloseTagContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] MarkdownPreprocessorParser.IdentifierContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.whitespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhitespace([NotNull] MarkdownPreprocessorParser.WhitespaceContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.space"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpace([NotNull] MarkdownPreprocessorParser.SpaceContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.tab"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTab([NotNull] MarkdownPreprocessorParser.TabContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.anyNonWhitespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnyNonWhitespace([NotNull] MarkdownPreprocessorParser.AnyNonWhitespaceContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.nonWhitespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonWhitespace([NotNull] MarkdownPreprocessorParser.NonWhitespaceContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MarkdownPreprocessorParser.anyWhitespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnyWhitespace([NotNull] MarkdownPreprocessorParser.AnyWhitespaceContext context);
}
} // namespace TxMark.Compiler
