//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\v-adai\Documents\Visual Studio 2015\Projects\TxMark\TxMark.Antlr\TxMarkParser.g4 by ANTLR 4.5-SNAPSHOT

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace TxMark.Compiler {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ITxMarkParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5-SNAPSHOT")]
[System.CLSCompliant(false)]
public partial class TxMarkParserBaseListener : ITxMarkParserListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>boldface</c>
	/// labeled alternative in <see cref="TxMarkParser.emphasis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoldface([NotNull] TxMarkParser.BoldfaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>boldface</c>
	/// labeled alternative in <see cref="TxMarkParser.emphasis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoldface([NotNull] TxMarkParser.BoldfaceContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>deleted</c>
	/// labeled alternative in <see cref="TxMarkParser.emphasis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeleted([NotNull] TxMarkParser.DeletedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>deleted</c>
	/// labeled alternative in <see cref="TxMarkParser.emphasis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeleted([NotNull] TxMarkParser.DeletedContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>superscript</c>
	/// labeled alternative in <see cref="TxMarkParser.emphasis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSuperscript([NotNull] TxMarkParser.SuperscriptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>superscript</c>
	/// labeled alternative in <see cref="TxMarkParser.emphasis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSuperscript([NotNull] TxMarkParser.SuperscriptContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>italics</c>
	/// labeled alternative in <see cref="TxMarkParser.emphasis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterItalics([NotNull] TxMarkParser.ItalicsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>italics</c>
	/// labeled alternative in <see cref="TxMarkParser.emphasis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitItalics([NotNull] TxMarkParser.ItalicsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>double_emphasis</c>
	/// labeled alternative in <see cref="TxMarkParser.emphasis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDouble_emphasis([NotNull] TxMarkParser.Double_emphasisContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>double_emphasis</c>
	/// labeled alternative in <see cref="TxMarkParser.emphasis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDouble_emphasis([NotNull] TxMarkParser.Double_emphasisContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>single_emphasis</c>
	/// labeled alternative in <see cref="TxMarkParser.emphasis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingle_emphasis([NotNull] TxMarkParser.Single_emphasisContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>single_emphasis</c>
	/// labeled alternative in <see cref="TxMarkParser.emphasis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingle_emphasis([NotNull] TxMarkParser.Single_emphasisContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.document"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDocument([NotNull] TxMarkParser.DocumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.document"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDocument([NotNull] TxMarkParser.DocumentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.word"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWord([NotNull] TxMarkParser.WordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.word"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWord([NotNull] TxMarkParser.WordContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.whitespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhitespace([NotNull] TxMarkParser.WhitespaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.whitespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhitespace([NotNull] TxMarkParser.WhitespaceContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.left_nametag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeft_nametag([NotNull] TxMarkParser.Left_nametagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.left_nametag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeft_nametag([NotNull] TxMarkParser.Left_nametagContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.right_nametag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRight_nametag([NotNull] TxMarkParser.Right_nametagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.right_nametag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRight_nametag([NotNull] TxMarkParser.Right_nametagContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] TxMarkParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] TxMarkParser.VariableContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.hookName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHookName([NotNull] TxMarkParser.HookNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.hookName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHookName([NotNull] TxMarkParser.HookNameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] TxMarkParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] TxMarkParser.NumberContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.quote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuote([NotNull] TxMarkParser.QuoteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.quote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuote([NotNull] TxMarkParser.QuoteContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.operand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperand([NotNull] TxMarkParser.OperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.operand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperand([NotNull] TxMarkParser.OperandContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.indexSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexSuffix([NotNull] TxMarkParser.IndexSuffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.indexSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexSuffix([NotNull] TxMarkParser.IndexSuffixContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.index_subexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndex_subexpression([NotNull] TxMarkParser.Index_subexpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.index_subexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndex_subexpression([NotNull] TxMarkParser.Index_subexpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.index_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndex_expression([NotNull] TxMarkParser.Index_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.index_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndex_expression([NotNull] TxMarkParser.Index_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.signed_index_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSigned_index_expression([NotNull] TxMarkParser.Signed_index_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.signed_index_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSigned_index_expression([NotNull] TxMarkParser.Signed_index_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.power_subexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPower_subexpression([NotNull] TxMarkParser.Power_subexpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.power_subexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPower_subexpression([NotNull] TxMarkParser.Power_subexpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.power_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPower_expression([NotNull] TxMarkParser.Power_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.power_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPower_expression([NotNull] TxMarkParser.Power_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.multiply_subexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiply_subexpression([NotNull] TxMarkParser.Multiply_subexpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.multiply_subexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiply_subexpression([NotNull] TxMarkParser.Multiply_subexpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.multiply_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiply_expression([NotNull] TxMarkParser.Multiply_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.multiply_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiply_expression([NotNull] TxMarkParser.Multiply_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.subequation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubequation([NotNull] TxMarkParser.SubequationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.subequation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubequation([NotNull] TxMarkParser.SubequationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.equation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEquation([NotNull] TxMarkParser.EquationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.equation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEquation([NotNull] TxMarkParser.EquationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.booleanOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBooleanOperator([NotNull] TxMarkParser.BooleanOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.booleanOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBooleanOperator([NotNull] TxMarkParser.BooleanOperatorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.subexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubexpression([NotNull] TxMarkParser.SubexpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.subexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubexpression([NotNull] TxMarkParser.SubexpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] TxMarkParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] TxMarkParser.ExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.constantTrue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstantTrue([NotNull] TxMarkParser.ConstantTrueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.constantTrue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstantTrue([NotNull] TxMarkParser.ConstantTrueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.constantFalse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstantFalse([NotNull] TxMarkParser.ConstantFalseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.constantFalse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstantFalse([NotNull] TxMarkParser.ConstantFalseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.constantNull"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstantNull([NotNull] TxMarkParser.ConstantNullContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.constantNull"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstantNull([NotNull] TxMarkParser.ConstantNullContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant([NotNull] TxMarkParser.ConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant([NotNull] TxMarkParser.ConstantContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.macroArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacroArgument([NotNull] TxMarkParser.MacroArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.macroArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacroArgument([NotNull] TxMarkParser.MacroArgumentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] TxMarkParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] TxMarkParser.LiteralContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.punctuation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPunctuation([NotNull] TxMarkParser.PunctuationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.punctuation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPunctuation([NotNull] TxMarkParser.PunctuationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.htmlOpenTag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtmlOpenTag([NotNull] TxMarkParser.HtmlOpenTagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.htmlOpenTag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtmlOpenTag([NotNull] TxMarkParser.HtmlOpenTagContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.htmlCloseTag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtmlCloseTag([NotNull] TxMarkParser.HtmlCloseTagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.htmlCloseTag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtmlCloseTag([NotNull] TxMarkParser.HtmlCloseTagContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.htmlElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtmlElement([NotNull] TxMarkParser.HtmlElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.htmlElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtmlElement([NotNull] TxMarkParser.HtmlElementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.emphasis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmphasis([NotNull] TxMarkParser.EmphasisContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.emphasis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmphasis([NotNull] TxMarkParser.EmphasisContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.muinuta"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMuinuta([NotNull] TxMarkParser.MuinutaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.muinuta"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMuinuta([NotNull] TxMarkParser.MuinutaContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.htmlAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtmlAttribute([NotNull] TxMarkParser.HtmlAttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.htmlAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtmlAttribute([NotNull] TxMarkParser.HtmlAttributeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.htmlAttributeValueContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtmlAttributeValueContent([NotNull] TxMarkParser.HtmlAttributeValueContentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.htmlAttributeValueContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtmlAttributeValueContent([NotNull] TxMarkParser.HtmlAttributeValueContentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.htmlAttributeValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtmlAttributeValue([NotNull] TxMarkParser.HtmlAttributeValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.htmlAttributeValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtmlAttributeValue([NotNull] TxMarkParser.HtmlAttributeValueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.script"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScript([NotNull] TxMarkParser.ScriptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.script"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScript([NotNull] TxMarkParser.ScriptContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.style"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStyle([NotNull] TxMarkParser.StyleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.style"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStyle([NotNull] TxMarkParser.StyleContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElement([NotNull] TxMarkParser.ElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElement([NotNull] TxMarkParser.ElementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContent([NotNull] TxMarkParser.ContentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContent([NotNull] TxMarkParser.ContentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.phrase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPhrase([NotNull] TxMarkParser.PhraseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.phrase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPhrase([NotNull] TxMarkParser.PhraseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.hook_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHook_clause([NotNull] TxMarkParser.Hook_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.hook_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHook_clause([NotNull] TxMarkParser.Hook_clauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.macro_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacro_clause([NotNull] TxMarkParser.Macro_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.macro_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacro_clause([NotNull] TxMarkParser.Macro_clauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.each_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEach_clause([NotNull] TxMarkParser.Each_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.each_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEach_clause([NotNull] TxMarkParser.Each_clauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.elseIf_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseIf_clause([NotNull] TxMarkParser.ElseIf_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.elseIf_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseIf_clause([NotNull] TxMarkParser.ElseIf_clauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.else_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse_clause([NotNull] TxMarkParser.Else_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.else_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse_clause([NotNull] TxMarkParser.Else_clauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.if_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_clause([NotNull] TxMarkParser.If_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.if_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_clause([NotNull] TxMarkParser.If_clauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.set_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSet_clause([NotNull] TxMarkParser.Set_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.set_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSet_clause([NotNull] TxMarkParser.Set_clauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.macro"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacro([NotNull] TxMarkParser.MacroContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.macro"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacro([NotNull] TxMarkParser.MacroContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.hook"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHook([NotNull] TxMarkParser.HookContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.hook"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHook([NotNull] TxMarkParser.HookContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TxMarkParser.macroName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacroName([NotNull] TxMarkParser.MacroNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TxMarkParser.macroName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacroName([NotNull] TxMarkParser.MacroNameContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace TxMark.Compiler
