//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\v-adai\Documents\Visual Studio 2015\Projects\TxMark\TxMark.Antlr\TxMarkParser.g4 by ANTLR 4.5-SNAPSHOT

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace TxMark.Compiler {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="TxMarkParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5-SNAPSHOT")]
[System.CLSCompliant(false)]
public interface ITxMarkParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by the <c>boldface</c>
	/// labeled alternative in <see cref="TxMarkParser.emphasis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoldface([NotNull] TxMarkParser.BoldfaceContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>deleted</c>
	/// labeled alternative in <see cref="TxMarkParser.emphasis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeleted([NotNull] TxMarkParser.DeletedContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>superscript</c>
	/// labeled alternative in <see cref="TxMarkParser.emphasis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuperscript([NotNull] TxMarkParser.SuperscriptContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>italics</c>
	/// labeled alternative in <see cref="TxMarkParser.emphasis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItalics([NotNull] TxMarkParser.ItalicsContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>double_emphasis</c>
	/// labeled alternative in <see cref="TxMarkParser.emphasis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDouble_emphasis([NotNull] TxMarkParser.Double_emphasisContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>single_emphasis</c>
	/// labeled alternative in <see cref="TxMarkParser.emphasis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingle_emphasis([NotNull] TxMarkParser.Single_emphasisContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDocument([NotNull] TxMarkParser.DocumentContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.whitespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhitespace([NotNull] TxMarkParser.WhitespaceContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.left_nametag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeft_nametag([NotNull] TxMarkParser.Left_nametagContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.right_nametag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRight_nametag([NotNull] TxMarkParser.Right_nametagContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] TxMarkParser.VariableContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.hookName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHookName([NotNull] TxMarkParser.HookNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.word"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWord([NotNull] TxMarkParser.WordContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] TxMarkParser.NumberContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.quote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuote([NotNull] TxMarkParser.QuoteContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperand([NotNull] TxMarkParser.OperandContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.indexSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexSuffix([NotNull] TxMarkParser.IndexSuffixContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.index_subexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex_subexpression([NotNull] TxMarkParser.Index_subexpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.index_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex_expression([NotNull] TxMarkParser.Index_expressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.signed_index_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSigned_index_expression([NotNull] TxMarkParser.Signed_index_expressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.power_subexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPower_subexpression([NotNull] TxMarkParser.Power_subexpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.power_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPower_expression([NotNull] TxMarkParser.Power_expressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.multiply_subexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiply_subexpression([NotNull] TxMarkParser.Multiply_subexpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.multiply_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiply_expression([NotNull] TxMarkParser.Multiply_expressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.subequation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubequation([NotNull] TxMarkParser.SubequationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.equation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquation([NotNull] TxMarkParser.EquationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.booleanOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanOperator([NotNull] TxMarkParser.BooleanOperatorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.subexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubexpression([NotNull] TxMarkParser.SubexpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] TxMarkParser.ExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.constantTrue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantTrue([NotNull] TxMarkParser.ConstantTrueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.constantFalse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantFalse([NotNull] TxMarkParser.ConstantFalseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.constantNull"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantNull([NotNull] TxMarkParser.ConstantNullContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] TxMarkParser.ConstantContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.macroArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacroArgument([NotNull] TxMarkParser.MacroArgumentContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] TxMarkParser.LiteralContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.punctuation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPunctuation([NotNull] TxMarkParser.PunctuationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.htmlOpenTag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHtmlOpenTag([NotNull] TxMarkParser.HtmlOpenTagContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.htmlCloseTag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHtmlCloseTag([NotNull] TxMarkParser.HtmlCloseTagContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.htmlElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHtmlElement([NotNull] TxMarkParser.HtmlElementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.emphasis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmphasis([NotNull] TxMarkParser.EmphasisContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.muinuta"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMuinuta([NotNull] TxMarkParser.MuinutaContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.htmlAttributeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHtmlAttributeName([NotNull] TxMarkParser.HtmlAttributeNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.htmlAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHtmlAttribute([NotNull] TxMarkParser.HtmlAttributeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.htmlAttributeValueContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHtmlAttributeValueContent([NotNull] TxMarkParser.HtmlAttributeValueContentContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.htmlAttributeValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHtmlAttributeValue([NotNull] TxMarkParser.HtmlAttributeValueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScript([NotNull] TxMarkParser.ScriptContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.style"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStyle([NotNull] TxMarkParser.StyleContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement([NotNull] TxMarkParser.ElementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContent([NotNull] TxMarkParser.ContentContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.phrase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPhrase([NotNull] TxMarkParser.PhraseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.hook_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHook_clause([NotNull] TxMarkParser.Hook_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.macro_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacro_clause([NotNull] TxMarkParser.Macro_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.each_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEach_clause([NotNull] TxMarkParser.Each_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.elseIf_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseIf_clause([NotNull] TxMarkParser.ElseIf_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.else_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse_clause([NotNull] TxMarkParser.Else_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.if_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_clause([NotNull] TxMarkParser.If_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.set_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet_clause([NotNull] TxMarkParser.Set_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.macro"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacro([NotNull] TxMarkParser.MacroContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.hook"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHook([NotNull] TxMarkParser.HookContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TxMarkParser.macroName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacroName([NotNull] TxMarkParser.MacroNameContext context);
}
} // namespace TxMark.Compiler
